services:
  graphdb:
    image: khaller/graphdb-free:9.11.2
    network_mode: "host"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: "host"
    depends_on:
      - graphdb
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: "host"
    depends_on:
      - backend
