import json

f = open("mapa-virtual.json")
bd = json.load(f)
f.close()

def prettify(a):
    return a.replace(" ", "_") if a else "NULL"

print("""@prefix : <http://rpcw.di.uminho.pt/2024/mapa-virtual/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <http://rpcw.di.uminho.pt/2024/mapa-virtual/> .

<http://rpcw.di.uminho.pt/2024/mapa-virtual> rdf:type owl:Ontology .

#################################################################
#    Object Properties
#################################################################

###  http://rpcw.di.uminho.pt/2024/mapa-virtual#LigacaoDestino
:LigacaoDestino rdf:type owl:ObjectProperty ;
                rdfs:domain :Ligacao ;
                rdfs:range :Cidade .


###  http://rpcw.di.uminho.pt/2024/mapa-virtual#LigacaoOrigem
:LigacaoOrigem rdf:type owl:ObjectProperty ;
               rdfs:domain :Ligacao ;
               rdfs:range :Cidade .


#################################################################
#    Data properties
#################################################################

###  http://rpcw.di.uminho.pt/2024/mapa-virtual#CidadeDescricao
:CidadeDescricao rdf:type owl:DatatypeProperty ;
                 rdfs:domain :Cidade ;
                 rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/mapa-virtual#CidadeDistrito
:CidadeDistrito rdf:type owl:DatatypeProperty ;
                rdfs:domain :Cidade ;
                rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/mapa-virtual#CidadeId
:CidadeId rdf:type owl:DatatypeProperty ;
          rdfs:domain :Cidade ;
          rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/mapa-virtual#CidadeNome
:CidadeNome rdf:type owl:DatatypeProperty ;
            rdfs:domain :Cidade ;
            rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/mapa-virtual#CidadePopulacao
:CidadePopulacao rdf:type owl:DatatypeProperty ;
                 rdfs:domain :Cidade ;
                 rdfs:range xsd:int .


###  http://rpcw.di.uminho.pt/2024/mapa-virtual#LigacaoDistancia
:LigacaoDistancia rdf:type owl:DatatypeProperty ;
                  rdfs:domain :Ligacao ;
                  rdfs:range xsd:float .


###  http://rpcw.di.uminho.pt/2024/mapa-virtual#LigacaoId
:LigacaoId rdf:type owl:DatatypeProperty ;
           rdfs:domain :Ligacao ;
           rdfs:range xsd:string .


###  http://www.w3.org/2002/07/owl#topDataProperty
owl:topDataProperty rdfs:domain :Cidade .


#################################################################
#    Classes
#################################################################

###  http://rpcw.di.uminho.pt/2024/mapa-virtual#Cidade
:Cidade rdf:type owl:Class .


###  http://rpcw.di.uminho.pt/2024/mapa-virtual#Ligacao
:Ligacao rdf:type owl:Class .


#################################################################
#    Individuals
#################################################################
""")

for cidade in bd["cidades"]:
    print(f"""
###  http://rpcw.di.uminho.pt/2024/mapa-virtual#{cidade["id"]}
:{cidade["id"]} rdf:type owl:NamedIndividual ,
              :Cidade ;
     :CidadeDescricao "{cidade["descrição"]}" ;
     :CidadeDistrito "{cidade["distrito"]}" ;
     :CidadeId "{cidade["id"]}" ;
     :CidadeNome "{cidade["nome"]}" ;
     :CidadePopulacao "{cidade["população"]}"^^xsd:int .
""")


for ligacao in bd["ligacoes"]:
    print(f"""
###  http://rpcw.di.uminho.pt/2024/mapa-virtual#{ligacao["id"]}
:{ligacao["id"]} rdf:type owl:NamedIndividual ,
             :Ligacao ;
    :LigacaoId :{ligacao["id"]} ;
    :LigacaoDestino :{ligacao["destino"]} ;
    :LigacaoOrigem :{ligacao["origem"]} ;
    :LigacaoDistancia "{ligacao["distância"]}"^^xsd:float .
""")

print("""
#################################################################
#    General axioms
#################################################################

[ rdf:type owl:AllDisjointClasses ;
  owl:members ( :Cidade
                :Ligacao
              )
] .


###  Generated by the OWL API (version 4.5.26.2023-07-17T20:34:13Z) https://github.com/owlcs/owlapi

""")