import json

f = open("alunos.json")
bd = json.load(f)
f.close()

print("""@prefix : <http://rpcw.di.uminho.pt/2024/alunos/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <http://rpcw.di.uminho.pt/2024/alunos/> .

<http://rpcw.di.uminho.pt/2024/alunos> rdf:type owl:Ontology .

#################################################################
#    Object Properties
#################################################################

###  http://rpcw.di.uminho.pt/2024/alunos#AlunoDidTPC
:AlunoDidTPC rdf:type owl:ObjectProperty ;
             rdfs:domain :Aluno ;
             rdfs:range :TPC .


#################################################################
#    Data properties
#################################################################

###  http://rpcw.di.uminho.pt/2024/alunos#AlunoCurso
:AlunoCurso rdf:type owl:DatatypeProperty ;
            rdfs:domain :Aluno ;
            rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/alunos#AlunoEspecial
:AlunoEspecial rdf:type owl:DatatypeProperty ;
               rdfs:domain :Aluno ;
               rdfs:range xsd:decimal .


###  http://rpcw.di.uminho.pt/2024/alunos#AlunoExame
:AlunoExame rdf:type owl:DatatypeProperty ;
            rdfs:domain :Aluno ;
            rdfs:range xsd:decimal .


###  http://rpcw.di.uminho.pt/2024/alunos#AlunoId
:AlunoId rdf:type owl:DatatypeProperty ;
         rdfs:domain :Aluno ;
         rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/alunos#AlunoNome
:AlunoNome rdf:type owl:DatatypeProperty ;
           rdfs:domain :Aluno ;
           rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/alunos#AlunoProjeto
:AlunoProjeto rdf:type owl:DatatypeProperty ;
              rdfs:domain :Aluno ;
              rdfs:range xsd:decimal .


###  http://rpcw.di.uminho.pt/2024/alunos#AlunoRecurso
:AlunoRecurso rdf:type owl:DatatypeProperty ;
              rdfs:domain :Aluno ;
              rdfs:range xsd:decimal .


###  http://rpcw.di.uminho.pt/2024/alunos#TPCNome
:TPCNome rdf:type owl:DatatypeProperty ;
         rdfs:domain :TPC ;
         rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/alunos#TPCNota
:TPCNota rdf:type owl:DatatypeProperty ;
         rdfs:domain :TPC ;
         rdfs:range xsd:decimal .


#################################################################
#    Classes
#################################################################

###  http://rpcw.di.uminho.pt/2024/alunos#Aluno
:Aluno rdf:type owl:Class .


###  http://rpcw.di.uminho.pt/2024/alunos#TPC
:TPC rdf:type owl:Class .


#################################################################
#    Individuals
#################################################################
""")

for aluno in bd["alunos"]:
    id = aluno["idAluno"]
    nome = aluno["nome"]
    curso = aluno["curso"]
    projeto = aluno["projeto"]

    print(f"""
###  http://rpcw.di.uminho.pt/2024/alunos#{id}
:{id} rdf:type owl:NamedIndividual ,
    :Aluno ;""")

    for k,v in aluno["exames"].items():
        if k == "normal":
            print(f"    :AlunoExame {v} ;")
        elif k == "recurso":
            print(f"    :AlunoRecurso {v} ;")
        elif k == "especial":
            print(f"    :AlunoEspecial {v} ;")

    tpcs = ""
    for tpc in aluno["tpc"]:
        tp = tpc["tp"]
        nota = tpc["nota"]
        print(f"    :AlunoDidTPC :{id}_{tp} ;")
        tpcs += f"""
###  http://rpcw.di.uminho.pt/2024/alunos#{id}_{tp}
:{id}_{tp} rdf:type owl:NamedIndividual ,
                       :TPC ;
              :TPCNome "{tp}" ;
              :TPCNota {nota} .
"""

    print(f"""    :AlunoCurso "{curso}" ;
    :AlunoId "{id}" ;
    :AlunoNome "{nome}" ;
    :AlunoProjeto {projeto} .
""")
    print(tpcs)

print("###  Generated by the OWL API (version 4.5.26.2023-07-17T20:34:13Z) https://github.com/owlcs/owlapi")